package lab2;

public interface Constants {
    String DRIVER_CHECK = "DRIVER_CHECK";
    String DRIVER_CONFIRM = "DRIVER_CONFIRM";
    String DRIVER_AVAILABLE = "DRIVER_AVAILABLE";
    String DRIVER_NOT_AVAILABLE = "DRIVER_NOT_AVAILABLE";
    String HOSTER_AVAILABLE = "HOSTER_AVAILABLE";
    String HOSTER_CHECK = "HOSTER_CHECK";
    String HOSTER_CONFIRM = "HOSTER_CONFIRM";
    String HOSTER_NOT_AVAILABLE = "HOSTER_NOT_AVAILABLE";
    int PERIOD_DAYS = 365;
}
